class CustomError(Exception):
    pass

raise CustomError("This is a custom exception.")
